version: "3.7"
services:
    backend:
        build: ./backend
        restart: always
        environment: 
          - SECRET_KEY=PfhE*M+H#4H=M^%@
        ports:
          - "8000:8000"
    frontend:
        build: ./frontend
        ports:
          - "3000:3000"         
        
     
