version: "3.7"
services:
    backend:
        build: ./backend
        restart: always
        ports:
          - "8000:8000"

    frontend:
        build: ./frontend
        ports:
          - "3000:3000"

           
        
     
